-- 智能拼写自动纠错词典 (已清洗重复项，修复了逻辑错误，剔除了高危误触项)

local abbreviations = {
  -- 关键字与基础语法
  tset = "test",
  tbale = "table",
  tabel = "table",
  fucniton = "function",
  funciton = "function",
  pirnt = "print",
  pritn = "print",
  cofnig = "config",
  cosnt = "const",
  scirpt = "script",
  whcih = "which",
  claer = "clear",
  celar = "clear",
  hte = "the",
  gti = "git",
  reuqire = "require",
  requrie = "require",
  reqire = "require",
  craete = "create",
  retunr = "return",
  retun = "return",
  returrn = "return",
  retrun = "return",
  reutrn = "return",
  reutnr = "return",
  reutn = "return",
  reurn = "return",
  ruetnr = "return",
  fi = "if",

  -- 包与模块
  apckage = "package",
  packcge = "package",
  pacakge = "package",
  packageg = "package",
  apckge = "package",
  packakge = "package",
  packaeg = "package",
  pakcage = "package",
  pakage = "package",
  pakcaeg = "package",
  pakcege = "package",
  pakckaeg = "package",
  acpakge = "package",
  packeg = "package",
  apckaeg = "package",
  pacakeg = "package",
  pakceeg = "package",
  packaegg = "package",
  apcakge = "package",

  -- 常用结构与类型
  ["mian()"] = "main()",
  ["maiN()"] = "main()",
  maiin = "main",
  mian = "main",
  Mdoel = "Model",
  mdoel = "model",
  strrut = "struct",
  sturct = "struct",
  strcut = "struct",
  sruct = "struct",
  funcc = "func",
  fucn = "func",
  filed = "field",
  Filed = "Field",
  tyep = "type",
  teyp = "type",
  ypte = "type",
  teypp = "type",

  -- 布尔值与 Import
  flase = "false",
  falsse = "false",
  falsee = "false",
  iimport = "import",
  imoprt = "import",
  imprt = "import",
  impot = "import",
  iimoprt = "import",
  importt = "import",

  -- 数据结构与错误处理
  errr = "err",
  eer = "err",
  eerr = "err",
  sting = "string",
  stirng = "string",
  vlaue = "value",
  valeu = "value",
  vlaues = "values",
  valeus = "values",
  idnex = "index",
  noed = "node",
  engien = "engine",
  Engien = "Engine",
  Wirter = "Writer",
  wirter = "writer",
  Wirte = "Write",
  wirte = "write",
  gorup = "group",
  Gorup = "Group",
  gourp = "group",
  Gourp = "Group",
  gruop = "group",
  Gruop = "Group",
  hahs = "hash",
  shcema = "schema",
  shceam = "schema",
  scheam = "schema",
  Shcema = "Schema",
  Shceam = "Schema",
  Scheam = "Schema",
  nmae = "name",
  Nmae = "Name",
}

-- 循环自动设置输入模式缩写
for wrong, right in pairs(abbreviations) do
  vim.cmd(string.format("iabbrev %s %s", wrong, right))
end
